GET https://prueba-server-node.onrender.com/api/tecnicos

####

POST https://prueba-server-node.onrender.com/api/tecnicos 
Content-Type: application/json

{
  "nombreTaller": "Rumos.Tec",
  "categoria": "0010"
}

####

DELETE https://prueba-server-node.onrender.com/api/tecnicos/2